export const TIMELINE_REQUEST = 'TIMELINE_REQUEST'
export const TIMELINE_SUCCESS = 'TIMELINE_SUCCESS'
export const TIMELINE_FAILURE = 'TIMELINE_FAILURE'

export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAILURE = 'PROFILE_FAILURE'
